import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta content={'Generated by create next app'} name={'description'} />
				<link href={'/favicon.ico'} rel={'icon'} />
			</Head>
			<h1 className={'text-4xl font-bold text-cyan-500'}>teste</h1>
		</div>
	);
};

export default Home;
